export const environment = {
    application_title: "The-PINK",
    api_base_url: "http://localhost:3000/api",
    endpoint_albums: "/albums",
    endpoint_songs: "/songs",
    endpoint_users: "/users",
    endpoint_login: "/login",
    request_method_get: "GET",
    count: 5,
    offset: 0,
    msg_input_all_fields: "Please input all the fields!",
    msg_password_not_match: "The confirm password is not matched!",
    msg_register_failed: "Failed to register!",
    msg_register_success: "User register successful!",
    footer_author_label: "@Author",
    footer_author_name: "Taingy Srun",
    footer_copyright: "All Rights Reserved.",
    home_welcome_to: "Welcome to",
    home_bp_inyourarea: "BLACKPINK in your area",
    home_my_bp_slogan: "To-the-Black To-the-Pink",
    home_bp_members: "Members: Jisoo, Jennie, Rosé, Lisa",
    label_adding_new_album: "Adding New Album",
    label_add_new_album: "Add New Album",
    label_adding_new_song: "Adding New Song",
    label_add_new_song: "Add New Song",
    label_title: "Title",
    label_released_date: "Released Date",
    label_btn_back: "< Back",
    label_btn_add: "Add",
    label_btn_save: "Save",
    label_btn_delete: "Delete",
    label_btn_edit: "Edit",
    label_song_list: "List of Songs",
    label_actions: "Actions",
    label_search: "Search",
    label_album_list: "List of Albums",
    label_btn_previous: "< Previous",
    label_btn_next: "Next >",
    label_editing_album: "Editing Album",
    label_editing_song: "Editing Song",
    label_btn_cancel: "Cancel",
    msg_page_not_found: "Ooooppp! looks like something went wrong!",
    label_name: "Name",
    label_username: "Username",
    label_password: "Password",
    label_login: "Login",
    label_logout: "Log out",
    nav_home: "Home",
    nav_albums: "Albums",
    nav_register: "Register",
    nav_profile: "Profile",
    nav_solo: "SOLO",
    label_profile: "Profile",
    label_registration_form: "Registration Form",
    label_confirm_password: "Confirm Password",
    label_register: "Register",
    label_welcome: "Welcome",
    
};
